# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reddit',
            options={'ordering': ['-num_comments']},
        ),
        migrations.RemoveField(
            model_name='reddit',
            name='my_field_name',
        ),
        migrations.AddField(
            model_name='reddit',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reddit',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reddit',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
