# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_slashdot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
