# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_hackernews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
