# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_remove_reddit_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
