# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_reddit_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reddit',
            options={'ordering': ['updated', 'num_comments']},
        ),
        migrations.AddField(
            model_name='slashdot',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slashdot',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slashdot',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
